/* automatically generated by rust-bindgen 0.72.0 */

pub const NVSDK_NGX_VERSION_API_MACRO: u32 = 21;
pub const NVSDK_NGX_EParameter_Reserved00: &[u8; 3] = b"#\0\0";
pub const NVSDK_NGX_EParameter_SuperSampling_Available: &[u8; 3] = b"#\x01\0";
pub const NVSDK_NGX_EParameter_InPainting_Available: &[u8; 3] = b"#\x02\0";
pub const NVSDK_NGX_EParameter_ImageSuperResolution_Available: &[u8; 3] = b"#\x03\0";
pub const NVSDK_NGX_EParameter_SlowMotion_Available: &[u8; 3] = b"#\x04\0";
pub const NVSDK_NGX_EParameter_VideoSuperResolution_Available: &[u8; 3] = b"#\x05\0";
pub const NVSDK_NGX_EParameter_Reserved06: &[u8; 3] = b"#\x06\0";
pub const NVSDK_NGX_EParameter_Reserved07: &[u8; 3] = b"#\x07\0";
pub const NVSDK_NGX_EParameter_Reserved08: &[u8; 3] = b"#\x08\0";
pub const NVSDK_NGX_EParameter_ImageSignalProcessing_Available: &[u8; 3] = b"#\t\0";
pub const NVSDK_NGX_EParameter_ImageSuperResolution_ScaleFactor_2_1: &[u8; 3] = b"#\n\0";
pub const NVSDK_NGX_EParameter_ImageSuperResolution_ScaleFactor_3_1: &[u8; 3] = b"#\x0B\0";
pub const NVSDK_NGX_EParameter_ImageSuperResolution_ScaleFactor_3_2: &[u8; 3] = b"#\x0C\0";
pub const NVSDK_NGX_EParameter_ImageSuperResolution_ScaleFactor_4_3: &[u8; 3] = b"#\r\0";
pub const NVSDK_NGX_EParameter_NumFrames: &[u8; 3] = b"#\x0E\0";
pub const NVSDK_NGX_EParameter_Scale: &[u8; 3] = b"#\x0F\0";
pub const NVSDK_NGX_EParameter_Width: &[u8; 3] = b"#\x10\0";
pub const NVSDK_NGX_EParameter_Height: &[u8; 3] = b"#\x11\0";
pub const NVSDK_NGX_EParameter_OutWidth: &[u8; 3] = b"#\x12\0";
pub const NVSDK_NGX_EParameter_OutHeight: &[u8; 3] = b"#\x13\0";
pub const NVSDK_NGX_EParameter_Sharpness: &[u8; 3] = b"#\x14\0";
pub const NVSDK_NGX_EParameter_Scratch: &[u8; 3] = b"#\x15\0";
pub const NVSDK_NGX_EParameter_Scratch_SizeInBytes: &[u8; 3] = b"#\x16\0";
pub const NVSDK_NGX_EParameter_EvaluationNode: &[u8; 3] = b"#\x17\0";
pub const NVSDK_NGX_EParameter_Input1: &[u8; 3] = b"#\x18\0";
pub const NVSDK_NGX_EParameter_Input1_Format: &[u8; 3] = b"#\x19\0";
pub const NVSDK_NGX_EParameter_Input1_SizeInBytes: &[u8; 3] = b"#\x1A\0";
pub const NVSDK_NGX_EParameter_Input2: &[u8; 3] = b"#\x1B\0";
pub const NVSDK_NGX_EParameter_Input2_Format: &[u8; 3] = b"#\x1C\0";
pub const NVSDK_NGX_EParameter_Input2_SizeInBytes: &[u8; 3] = b"#\x1D\0";
pub const NVSDK_NGX_EParameter_Color: &[u8; 3] = b"#\x1E\0";
pub const NVSDK_NGX_EParameter_Color_Format: &[u8; 3] = b"#\x1F\0";
pub const NVSDK_NGX_EParameter_Color_SizeInBytes: &[u8; 3] = b"# \0";
pub const NVSDK_NGX_EParameter_Albedo: &[u8; 3] = b"#!\0";
pub const NVSDK_NGX_EParameter_Output: &[u8; 3] = b"#\"\0";
pub const NVSDK_NGX_EParameter_Output_Format: &[u8; 3] = b"##\0";
pub const NVSDK_NGX_EParameter_Output_SizeInBytes: &[u8; 3] = b"#$\0";
pub const NVSDK_NGX_EParameter_Reset: &[u8; 3] = b"#%\0";
pub const NVSDK_NGX_EParameter_BlendFactor: &[u8; 3] = b"#&\0";
pub const NVSDK_NGX_EParameter_MotionVectors: &[u8; 3] = b"#'\0";
pub const NVSDK_NGX_EParameter_Rect_X: &[u8; 3] = b"#(\0";
pub const NVSDK_NGX_EParameter_Rect_Y: &[u8; 3] = b"#)\0";
pub const NVSDK_NGX_EParameter_Rect_W: &[u8; 3] = b"#*\0";
pub const NVSDK_NGX_EParameter_Rect_H: &[u8; 3] = b"#+\0";
pub const NVSDK_NGX_EParameter_MV_Scale_X: &[u8; 3] = b"#,\0";
pub const NVSDK_NGX_EParameter_MV_Scale_Y: &[u8; 3] = b"#-\0";
pub const NVSDK_NGX_EParameter_Model: &[u8; 3] = b"#.\0";
pub const NVSDK_NGX_EParameter_Format: &[u8; 3] = b"#/\0";
pub const NVSDK_NGX_EParameter_SizeInBytes: &[u8; 3] = b"#0\0";
pub const NVSDK_NGX_EParameter_ResourceAllocCallback: &[u8; 3] = b"#1\0";
pub const NVSDK_NGX_EParameter_BufferAllocCallback: &[u8; 3] = b"#2\0";
pub const NVSDK_NGX_EParameter_Tex2DAllocCallback: &[u8; 3] = b"#3\0";
pub const NVSDK_NGX_EParameter_ResourceReleaseCallback: &[u8; 3] = b"#4\0";
pub const NVSDK_NGX_EParameter_CreationNodeMask: &[u8; 3] = b"#5\0";
pub const NVSDK_NGX_EParameter_VisibilityNodeMask: &[u8; 3] = b"#6\0";
pub const NVSDK_NGX_EParameter_PreviousOutput: &[u8; 3] = b"#7\0";
pub const NVSDK_NGX_EParameter_MV_Offset_X: &[u8; 3] = b"#8\0";
pub const NVSDK_NGX_EParameter_MV_Offset_Y: &[u8; 3] = b"#9\0";
pub const NVSDK_NGX_EParameter_Hint_UseFireflySwatter: &[u8; 3] = b"#:\0";
pub const NVSDK_NGX_EParameter_Resource_Width: &[u8; 3] = b"#;\0";
pub const NVSDK_NGX_EParameter_Resource_Height: &[u8; 3] = b"#<\0";
pub const NVSDK_NGX_EParameter_Depth: &[u8; 3] = b"#=\0";
pub const NVSDK_NGX_EParameter_DLSSOptimalSettingsCallback: &[u8; 3] = b"#>\0";
pub const NVSDK_NGX_EParameter_PerfQualityValue: &[u8; 3] = b"#?\0";
pub const NVSDK_NGX_EParameter_RTXValue: &[u8; 3] = b"#@\0";
pub const NVSDK_NGX_EParameter_DLSSMode: &[u8; 3] = b"#A\0";
pub const NVSDK_NGX_EParameter_DeepResolve_Available: &[u8; 3] = b"#B\0";
pub const NVSDK_NGX_EParameter_Deprecated_43: &[u8; 3] = b"#C\0";
pub const NVSDK_NGX_EParameter_OptLevel: &[u8; 3] = b"#D\0";
pub const NVSDK_NGX_EParameter_IsDevSnippetBranch: &[u8; 3] = b"#E\0";
pub const NVSDK_NGX_EParameter_DeepDVC_Available: &[u8; 3] = b"#F\0";
pub const NVSDK_NGX_EParameter_Graphics_API: &[u8; 3] = b"#G\0";
pub const NVSDK_NGX_EParameter_Reserved_48: &[u8; 3] = b"#H\0";
pub const NVSDK_NGX_EParameter_Reserved_49: &[u8; 3] = b"#I\0";
pub const NVSDK_NGX_Parameter_OptLevel: &[u8; 17] = b"Snippet.OptLevel\0";
pub const NVSDK_NGX_Parameter_IsDevSnippetBranch: &[u8; 20] = b"Snippet.IsDevBranch\0";
pub const NVSDK_NGX_Parameter_SuperSampling_ScaleFactor: &[u8; 26] = b"SuperSampling.ScaleFactor\0";
pub const NVSDK_NGX_Parameter_ImageSignalProcessing_ScaleFactor: &[u8; 34] =
    b"ImageSignalProcessing.ScaleFactor\0";
pub const NVSDK_NGX_Parameter_SuperSampling_Available: &[u8; 24] = b"SuperSampling.Available\0";
pub const NVSDK_NGX_Parameter_InPainting_Available: &[u8; 21] = b"InPainting.Available\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_Available: &[u8; 31] =
    b"ImageSuperResolution.Available\0";
pub const NVSDK_NGX_Parameter_SlowMotion_Available: &[u8; 21] = b"SlowMotion.Available\0";
pub const NVSDK_NGX_Parameter_VideoSuperResolution_Available: &[u8; 31] =
    b"VideoSuperResolution.Available\0";
pub const NVSDK_NGX_Parameter_ImageSignalProcessing_Available: &[u8; 32] =
    b"ImageSignalProcessing.Available\0";
pub const NVSDK_NGX_Parameter_DeepResolve_Available: &[u8; 22] = b"DeepResolve.Available\0";
pub const NVSDK_NGX_Parameter_SuperSampling_NeedsUpdatedDriver: &[u8; 33] =
    b"SuperSampling.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_InPainting_NeedsUpdatedDriver: &[u8; 30] =
    b"InPainting.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_NeedsUpdatedDriver: &[u8; 40] =
    b"ImageSuperResolution.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_SlowMotion_NeedsUpdatedDriver: &[u8; 30] =
    b"SlowMotion.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_VideoSuperResolution_NeedsUpdatedDriver: &[u8; 40] =
    b"VideoSuperResolution.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_ImageSignalProcessing_NeedsUpdatedDriver: &[u8; 41] =
    b"ImageSignalProcessing.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_DeepResolve_NeedsUpdatedDriver: &[u8; 31] =
    b"DeepResolve.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_FrameInterpolation_NeedsUpdatedDriver: &[u8; 38] =
    b"FrameInterpolation.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_SuperSampling_MinDriverVersionMajor: &[u8; 36] =
    b"SuperSampling.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_InPainting_MinDriverVersionMajor: &[u8; 33] =
    b"InPainting.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_MinDriverVersionMajor: &[u8; 43] =
    b"ImageSuperResolution.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_SlowMotion_MinDriverVersionMajor: &[u8; 33] =
    b"SlowMotion.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_VideoSuperResolution_MinDriverVersionMajor: &[u8; 43] =
    b"VideoSuperResolution.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_ImageSignalProcessing_MinDriverVersionMajor: &[u8; 44] =
    b"ImageSignalProcessing.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_DeepResolve_MinDriverVersionMajor: &[u8; 34] =
    b"DeepResolve.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_FrameInterpolation_MinDriverVersionMajor: &[u8; 41] =
    b"FrameInterpolation.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_SuperSampling_MinDriverVersionMinor: &[u8; 36] =
    b"SuperSampling.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_InPainting_MinDriverVersionMinor: &[u8; 33] =
    b"InPainting.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_MinDriverVersionMinor: &[u8; 43] =
    b"ImageSuperResolution.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_SlowMotion_MinDriverVersionMinor: &[u8; 33] =
    b"SlowMotion.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_VideoSuperResolution_MinDriverVersionMinor: &[u8; 43] =
    b"VideoSuperResolution.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_ImageSignalProcessing_MinDriverVersionMinor: &[u8; 44] =
    b"ImageSignalProcessing.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_DeepResolve_MinDriverVersionMinor: &[u8; 34] =
    b"DeepResolve.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_SuperSampling_FeatureInitResult: &[u8; 32] =
    b"SuperSampling.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_InPainting_FeatureInitResult: &[u8; 29] =
    b"InPainting.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_FeatureInitResult: &[u8; 39] =
    b"ImageSuperResolution.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_SlowMotion_FeatureInitResult: &[u8; 29] =
    b"SlowMotion.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_VideoSuperResolution_FeatureInitResult: &[u8; 39] =
    b"VideoSuperResolution.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_ImageSignalProcessing_FeatureInitResult: &[u8; 40] =
    b"ImageSignalProcessing.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_DeepResolve_FeatureInitResult: &[u8; 30] =
    b"DeepResolve.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_FrameInterpolation_FeatureInitResult: &[u8; 37] =
    b"FrameInterpolation.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_ScaleFactor_2_1: &[u8; 37] =
    b"ImageSuperResolution.ScaleFactor.2.1\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_ScaleFactor_3_1: &[u8; 37] =
    b"ImageSuperResolution.ScaleFactor.3.1\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_ScaleFactor_3_2: &[u8; 37] =
    b"ImageSuperResolution.ScaleFactor.3.2\0";
pub const NVSDK_NGX_Parameter_ImageSuperResolution_ScaleFactor_4_3: &[u8; 37] =
    b"ImageSuperResolution.ScaleFactor.4.3\0";
pub const NVSDK_NGX_Parameter_NumFrames: &[u8; 10] = b"NumFrames\0";
pub const NVSDK_NGX_Parameter_Scale: &[u8; 6] = b"Scale\0";
pub const NVSDK_NGX_Parameter_Width: &[u8; 6] = b"Width\0";
pub const NVSDK_NGX_Parameter_Height: &[u8; 7] = b"Height\0";
pub const NVSDK_NGX_Parameter_OutWidth: &[u8; 9] = b"OutWidth\0";
pub const NVSDK_NGX_Parameter_OutHeight: &[u8; 10] = b"OutHeight\0";
pub const NVSDK_NGX_Parameter_Sharpness: &[u8; 10] = b"Sharpness\0";
pub const NVSDK_NGX_Parameter_Scratch: &[u8; 8] = b"Scratch\0";
pub const NVSDK_NGX_Parameter_Scratch_SizeInBytes: &[u8; 20] = b"Scratch.SizeInBytes\0";
pub const NVSDK_NGX_Parameter_Input1: &[u8; 7] = b"Input1\0";
pub const NVSDK_NGX_Parameter_Input1_Format: &[u8; 14] = b"Input1.Format\0";
pub const NVSDK_NGX_Parameter_Input1_SizeInBytes: &[u8; 19] = b"Input1.SizeInBytes\0";
pub const NVSDK_NGX_Parameter_Input2: &[u8; 7] = b"Input2\0";
pub const NVSDK_NGX_Parameter_Input2_Format: &[u8; 14] = b"Input2.Format\0";
pub const NVSDK_NGX_Parameter_Input2_SizeInBytes: &[u8; 19] = b"Input2.SizeInBytes\0";
pub const NVSDK_NGX_Parameter_Color: &[u8; 6] = b"Color\0";
pub const NVSDK_NGX_Parameter_Color_Format: &[u8; 13] = b"Color.Format\0";
pub const NVSDK_NGX_Parameter_Color_SizeInBytes: &[u8; 18] = b"Color.SizeInBytes\0";
pub const NVSDK_NGX_Parameter_FI_Color1: &[u8; 7] = b"Color1\0";
pub const NVSDK_NGX_Parameter_FI_Color2: &[u8; 7] = b"Color2\0";
pub const NVSDK_NGX_Parameter_Albedo: &[u8; 7] = b"Albedo\0";
pub const NVSDK_NGX_Parameter_Output: &[u8; 7] = b"Output\0";
pub const NVSDK_NGX_Parameter_Output_Format: &[u8; 14] = b"Output.Format\0";
pub const NVSDK_NGX_Parameter_Output_SizeInBytes: &[u8; 19] = b"Output.SizeInBytes\0";
pub const NVSDK_NGX_Parameter_FI_Output1: &[u8; 8] = b"Output1\0";
pub const NVSDK_NGX_Parameter_FI_Output2: &[u8; 8] = b"Output2\0";
pub const NVSDK_NGX_Parameter_FI_Output3: &[u8; 8] = b"Output3\0";
pub const NVSDK_NGX_Parameter_Reset: &[u8; 6] = b"Reset\0";
pub const NVSDK_NGX_Parameter_BlendFactor: &[u8; 12] = b"BlendFactor\0";
pub const NVSDK_NGX_Parameter_MotionVectors: &[u8; 14] = b"MotionVectors\0";
pub const NVSDK_NGX_Parameter_FI_MotionVectors1: &[u8; 15] = b"MotionVectors1\0";
pub const NVSDK_NGX_Parameter_FI_MotionVectors2: &[u8; 15] = b"MotionVectors2\0";
pub const NVSDK_NGX_Parameter_Rect_X: &[u8; 7] = b"Rect.X\0";
pub const NVSDK_NGX_Parameter_Rect_Y: &[u8; 7] = b"Rect.Y\0";
pub const NVSDK_NGX_Parameter_Rect_W: &[u8; 7] = b"Rect.W\0";
pub const NVSDK_NGX_Parameter_Rect_H: &[u8; 7] = b"Rect.H\0";
pub const NVSDK_NGX_Parameter_OutRect_X: &[u8; 10] = b"OutRect.X\0";
pub const NVSDK_NGX_Parameter_OutRect_Y: &[u8; 10] = b"OutRect.Y\0";
pub const NVSDK_NGX_Parameter_OutRect_W: &[u8; 10] = b"OutRect.W\0";
pub const NVSDK_NGX_Parameter_OutRect_H: &[u8; 10] = b"OutRect.H\0";
pub const NVSDK_NGX_Parameter_MV_Scale_X: &[u8; 11] = b"MV.Scale.X\0";
pub const NVSDK_NGX_Parameter_MV_Scale_Y: &[u8; 11] = b"MV.Scale.Y\0";
pub const NVSDK_NGX_Parameter_Model: &[u8; 6] = b"Model\0";
pub const NVSDK_NGX_Parameter_Format: &[u8; 7] = b"Format\0";
pub const NVSDK_NGX_Parameter_SizeInBytes: &[u8; 12] = b"SizeInBytes\0";
pub const NVSDK_NGX_Parameter_ResourceAllocCallback: &[u8; 22] = b"ResourceAllocCallback\0";
pub const NVSDK_NGX_Parameter_BufferAllocCallback: &[u8; 20] = b"BufferAllocCallback\0";
pub const NVSDK_NGX_Parameter_Tex2DAllocCallback: &[u8; 19] = b"Tex2DAllocCallback\0";
pub const NVSDK_NGX_Parameter_ResourceReleaseCallback: &[u8; 24] = b"ResourceReleaseCallback\0";
pub const NVSDK_NGX_Parameter_CreationNodeMask: &[u8; 17] = b"CreationNodeMask\0";
pub const NVSDK_NGX_Parameter_VisibilityNodeMask: &[u8; 19] = b"VisibilityNodeMask\0";
pub const NVSDK_NGX_Parameter_MV_Offset_X: &[u8; 12] = b"MV.Offset.X\0";
pub const NVSDK_NGX_Parameter_MV_Offset_Y: &[u8; 12] = b"MV.Offset.Y\0";
pub const NVSDK_NGX_Parameter_Hint_UseFireflySwatter: &[u8; 23] = b"Hint.UseFireflySwatter\0";
pub const NVSDK_NGX_Parameter_Resource_Width: &[u8; 14] = b"ResourceWidth\0";
pub const NVSDK_NGX_Parameter_Resource_Height: &[u8; 15] = b"ResourceHeight\0";
pub const NVSDK_NGX_Parameter_Resource_OutWidth: &[u8; 17] = b"ResourceOutWidth\0";
pub const NVSDK_NGX_Parameter_Resource_OutHeight: &[u8; 18] = b"ResourceOutHeight\0";
pub const NVSDK_NGX_Parameter_Depth: &[u8; 6] = b"Depth\0";
pub const NVSDK_NGX_Parameter_FI_Depth1: &[u8; 7] = b"Depth1\0";
pub const NVSDK_NGX_Parameter_FI_Depth2: &[u8; 7] = b"Depth2\0";
pub const NVSDK_NGX_Parameter_DLSSOptimalSettingsCallback: &[u8; 28] =
    b"DLSSOptimalSettingsCallback\0";
pub const NVSDK_NGX_Parameter_DLSSGetStatsCallback: &[u8; 21] = b"DLSSGetStatsCallback\0";
pub const NVSDK_NGX_Parameter_PerfQualityValue: &[u8; 17] = b"PerfQualityValue\0";
pub const NVSDK_NGX_Parameter_RTXValue: &[u8; 9] = b"RTXValue\0";
pub const NVSDK_NGX_Parameter_DLSSMode: &[u8; 9] = b"DLSSMode\0";
pub const NVSDK_NGX_Parameter_FI_Mode: &[u8; 7] = b"FIMode\0";
pub const NVSDK_NGX_Parameter_FI_OF_Preset: &[u8; 11] = b"FIOFPreset\0";
pub const NVSDK_NGX_Parameter_FI_OF_GridSize: &[u8; 13] = b"FIOFGridSize\0";
pub const NVSDK_NGX_Parameter_Jitter_Offset_X: &[u8; 16] = b"Jitter.Offset.X\0";
pub const NVSDK_NGX_Parameter_Jitter_Offset_Y: &[u8; 16] = b"Jitter.Offset.Y\0";
pub const NVSDK_NGX_Parameter_Denoise: &[u8; 8] = b"Denoise\0";
pub const NVSDK_NGX_Parameter_TransparencyMask: &[u8; 17] = b"TransparencyMask\0";
pub const NVSDK_NGX_Parameter_ExposureTexture: &[u8; 16] = b"ExposureTexture\0";
pub const NVSDK_NGX_Parameter_DLSS_Feature_Create_Flags: &[u8; 26] = b"DLSS.Feature.Create.Flags\0";
pub const NVSDK_NGX_Parameter_DLSS_Checkerboard_Jitter_Hack: &[u8; 30] =
    b"DLSS.Checkerboard.Jitter.Hack\0";
pub const NVSDK_NGX_Parameter_GBuffer_Normals: &[u8; 16] = b"GBuffer.Normals\0";
pub const NVSDK_NGX_Parameter_GBuffer_Albedo: &[u8; 15] = b"GBuffer.Albedo\0";
pub const NVSDK_NGX_Parameter_GBuffer_Roughness: &[u8; 18] = b"GBuffer.Roughness\0";
pub const NVSDK_NGX_Parameter_GBuffer_DiffuseAlbedo: &[u8; 22] = b"GBuffer.DiffuseAlbedo\0";
pub const NVSDK_NGX_Parameter_GBuffer_SpecularAlbedo: &[u8; 23] = b"GBuffer.SpecularAlbedo\0";
pub const NVSDK_NGX_Parameter_GBuffer_IndirectAlbedo: &[u8; 23] = b"GBuffer.IndirectAlbedo\0";
pub const NVSDK_NGX_Parameter_GBuffer_SpecularMvec: &[u8; 21] = b"GBuffer.SpecularMvec\0";
pub const NVSDK_NGX_Parameter_GBuffer_DisocclusionMask: &[u8; 25] = b"GBuffer.DisocclusionMask\0";
pub const NVSDK_NGX_Parameter_GBuffer_Metallic: &[u8; 17] = b"GBuffer.Metallic\0";
pub const NVSDK_NGX_Parameter_GBuffer_Specular: &[u8; 17] = b"GBuffer.Specular\0";
pub const NVSDK_NGX_Parameter_GBuffer_Subsurface: &[u8; 19] = b"GBuffer.Subsurface\0";
pub const NVSDK_NGX_Parameter_GBuffer_ShadingModelId: &[u8; 23] = b"GBuffer.ShadingModelId\0";
pub const NVSDK_NGX_Parameter_GBuffer_MaterialId: &[u8; 19] = b"GBuffer.MaterialId\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_8: &[u8; 17] = b"GBuffer.Attrib.8\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_9: &[u8; 17] = b"GBuffer.Attrib.9\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_10: &[u8; 18] = b"GBuffer.Attrib.10\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_11: &[u8; 18] = b"GBuffer.Attrib.11\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_12: &[u8; 18] = b"GBuffer.Attrib.12\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_13: &[u8; 18] = b"GBuffer.Attrib.13\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_14: &[u8; 18] = b"GBuffer.Attrib.14\0";
pub const NVSDK_NGX_Parameter_GBuffer_Atrrib_15: &[u8; 18] = b"GBuffer.Attrib.15\0";
pub const NVSDK_NGX_Parameter_TonemapperType: &[u8; 15] = b"TonemapperType\0";
pub const NVSDK_NGX_Parameter_FreeMemOnReleaseFeature: &[u8; 24] = b"FreeMemOnReleaseFeature\0";
pub const NVSDK_NGX_Parameter_MotionVectors3D: &[u8; 16] = b"MotionVectors3D\0";
pub const NVSDK_NGX_Parameter_IsParticleMask: &[u8; 15] = b"IsParticleMask\0";
pub const NVSDK_NGX_Parameter_AnimatedTextureMask: &[u8; 20] = b"AnimatedTextureMask\0";
pub const NVSDK_NGX_Parameter_DepthHighRes: &[u8; 13] = b"DepthHighRes\0";
pub const NVSDK_NGX_Parameter_Position_ViewSpace: &[u8; 19] = b"Position.ViewSpace\0";
pub const NVSDK_NGX_Parameter_FrameTimeDeltaInMsec: &[u8; 21] = b"FrameTimeDeltaInMsec\0";
pub const NVSDK_NGX_Parameter_RayTracingHitDistance: &[u8; 22] = b"RayTracingHitDistance\0";
pub const NVSDK_NGX_Parameter_MotionVectorsReflection: &[u8; 24] = b"MotionVectorsReflection\0";
pub const NVSDK_NGX_Parameter_DLSS_Enable_Output_Subrects: &[u8; 28] =
    b"DLSS.Enable.Output.Subrects\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Color_Subrect_Base_X: &[u8; 32] =
    b"DLSS.Input.Color.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Color_Subrect_Base_Y: &[u8; 32] =
    b"DLSS.Input.Color.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Depth_Subrect_Base_X: &[u8; 32] =
    b"DLSS.Input.Depth.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Depth_Subrect_Base_Y: &[u8; 32] =
    b"DLSS.Input.Depth.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_MV_SubrectBase_X: &[u8; 29] =
    b"DLSS.Input.MV.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_MV_SubrectBase_Y: &[u8; 29] =
    b"DLSS.Input.MV.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Translucency_SubrectBase_X: &[u8; 39] =
    b"DLSS.Input.Translucency.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Translucency_SubrectBase_Y: &[u8; 39] =
    b"DLSS.Input.Translucency.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Output_Subrect_Base_X: &[u8; 27] =
    b"DLSS.Output.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Output_Subrect_Base_Y: &[u8; 27] =
    b"DLSS.Output.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Render_Subrect_Dimensions_Width: &[u8; 37] =
    b"DLSS.Render.Subrect.Dimensions.Width\0";
pub const NVSDK_NGX_Parameter_DLSS_Render_Subrect_Dimensions_Height: &[u8; 38] =
    b"DLSS.Render.Subrect.Dimensions.Height\0";
pub const NVSDK_NGX_Parameter_DLSS_Pre_Exposure: &[u8; 18] = b"DLSS.Pre.Exposure\0";
pub const NVSDK_NGX_Parameter_DLSS_Exposure_Scale: &[u8; 20] = b"DLSS.Exposure.Scale\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Bias_Current_Color_Mask: &[u8; 35] =
    b"DLSS.Input.Bias.Current.Color.Mask\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Bias_Current_Color_SubrectBase_X: &[u8; 45] =
    b"DLSS.Input.Bias.Current.Color.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Bias_Current_Color_SubrectBase_Y: &[u8; 45] =
    b"DLSS.Input.Bias.Current.Color.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Indicator_Invert_Y_Axis: &[u8; 29] =
    b"DLSS.Indicator.Invert.Y.Axis\0";
pub const NVSDK_NGX_Parameter_DLSS_Indicator_Invert_X_Axis: &[u8; 29] =
    b"DLSS.Indicator.Invert.X.Axis\0";
pub const NVSDK_NGX_Parameter_DLSS_INV_VIEW_PROJECTION_MATRIX: &[u8; 24] =
    b"InvViewProjectionMatrix\0";
pub const NVSDK_NGX_Parameter_DLSS_CLIP_TO_PREV_CLIP_MATRIX: &[u8; 21] = b"ClipToPrevClipMatrix\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayer: &[u8; 23] = b"DLSS.TransparencyLayer\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayer_Subrect_Base_X: &[u8; 38] =
    b"DLSS.TransparencyLayer.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayer_Subrect_Base_Y: &[u8; 38] =
    b"DLSS.TransparencyLayer.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayerOpacity: &[u8; 30] =
    b"DLSS.TransparencyLayerOpacity\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayerOpacity_Subrect_Base_X: &[u8; 45] =
    b"DLSS.TransparencyLayerOpacity.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayerOpacity_Subrect_Base_Y: &[u8; 45] =
    b"DLSS.TransparencyLayerOpacity.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayerMvecs: &[u8; 28] =
    b"DLSS.TransparencyLayerMvecs\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayerMvecs_Subrect_Base_X: &[u8; 43] =
    b"DLSS.TransparencyLayerMvecs.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_TransparencyLayerMvecs_Subrect_Base_Y: &[u8; 43] =
    b"DLSS.TransparencyLayerMvecs.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_DisocclusionMask: &[u8; 22] = b"DLSS.DisocclusionMask\0";
pub const NVSDK_NGX_Parameter_DLSS_DisocclusionMask_Subrect_Base_X: &[u8; 37] =
    b"DLSS.DisocclusionMask.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_DisocclusionMask_Subrect_Base_Y: &[u8; 37] =
    b"DLSS.DisocclusionMask.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Get_Dynamic_Max_Render_Width: &[u8; 34] =
    b"DLSS.Get.Dynamic.Max.Render.Width\0";
pub const NVSDK_NGX_Parameter_DLSS_Get_Dynamic_Max_Render_Height: &[u8; 35] =
    b"DLSS.Get.Dynamic.Max.Render.Height\0";
pub const NVSDK_NGX_Parameter_DLSS_Get_Dynamic_Min_Render_Width: &[u8; 34] =
    b"DLSS.Get.Dynamic.Min.Render.Width\0";
pub const NVSDK_NGX_Parameter_DLSS_Get_Dynamic_Min_Render_Height: &[u8; 35] =
    b"DLSS.Get.Dynamic.Min.Render.Height\0";
pub const NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_DLAA: &[u8; 29] =
    b"DLSS.Hint.Render.Preset.DLAA\0";
pub const NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Quality: &[u8; 32] =
    b"DLSS.Hint.Render.Preset.Quality\0";
pub const NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Balanced: &[u8; 33] =
    b"DLSS.Hint.Render.Preset.Balanced\0";
pub const NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_Performance: &[u8; 36] =
    b"DLSS.Hint.Render.Preset.Performance\0";
pub const NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraPerformance: &[u8; 41] =
    b"DLSS.Hint.Render.Preset.UltraPerformance\0";
pub const NVSDK_NGX_Parameter_DLSS_Hint_Render_Preset_UltraQuality: &[u8; 37] =
    b"DLSS.Hint.Render.Preset.UltraQuality\0";
pub const NVSDK_NGX_Parameter_DLSS_Denoise_Mode: &[u8; 18] = b"DLSS.Denoise.Mode\0";
pub const NVSDK_NGX_Parameter_DLSS_Roughness_Mode: &[u8; 20] = b"DLSS.Roughness.Mode\0";
pub const NVSDK_NGX_Parameter_DiffuseAlbedo: &[u8; 25] = b"DLSS.Input.DiffuseAlbedo\0";
pub const NVSDK_NGX_Parameter_SpecularAlbedo: &[u8; 26] = b"DLSS.Input.SpecularAlbedo\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_DiffuseAlbedo_Subrect_Base_X: &[u8; 40] =
    b"DLSS.Input.DiffuseAlbedo.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_DiffuseAlbedo_Subrect_Base_Y: &[u8; 40] =
    b"DLSS.Input.DiffuseAlbedo.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_SpecularAlbedo_Subrect_Base_X: &[u8; 41] =
    b"DLSS.Input.SpecularAlbedo.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_SpecularAlbedo_Subrect_Base_Y: &[u8; 41] =
    b"DLSS.Input.SpecularAlbedo.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Normals_Subrect_Base_X: &[u8; 34] =
    b"DLSS.Input.Normals.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Normals_Subrect_Base_Y: &[u8; 34] =
    b"DLSS.Input.Normals.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Roughness_Subrect_Base_X: &[u8; 36] =
    b"DLSS.Input.Roughness.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSS_Input_Roughness_Subrect_Base_Y: &[u8; 36] =
    b"DLSS.Input.Roughness.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_ViewToClipMatrix: &[u8; 17] = b"ViewToClipMatrix\0";
pub const NVSDK_NGX_Parameter_GBuffer_Emissive: &[u8; 17] = b"GBuffer.Emissive\0";
pub const NVSDK_NGX_Parameter_Use_Folded_Network: &[u8; 24] = b"DLSS.Use.Folded.Network\0";
pub const NVSDK_NGX_Parameter_Diffuse_Ray_Direction: &[u8; 22] = b"Diffuse.Ray.Direction\0";
pub const NVSDK_NGX_Parameter_DLSS_WORLD_TO_VIEW_MATRIX: &[u8; 18] = b"WorldToViewMatrix\0";
pub const NVSDK_NGX_Parameter_DLSS_VIEW_TO_CLIP_MATRIX: &[u8; 17] = b"ViewToClipMatrix\0";
pub const NVSDK_NGX_Parameter_Use_HW_Depth: &[u8; 18] = b"DLSS.Use.HW.Depth\0";
pub const NVSDK_NGX_Parameter_DLSSD_ReflectedAlbedo: &[u8; 22] = b"DLSSD.ReflectedAlbedo\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeParticles: &[u8; 27] =
    b"DLSSD.ColorBeforeParticles\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterParticles: &[u8; 26] = b"DLSSD.ColorAfterParticles\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeTransparency: &[u8; 30] =
    b"DLSSD.ColorBeforeTransparency\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterTransparency: &[u8; 29] =
    b"DLSSD.ColorAfterTransparency\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeFog: &[u8; 21] = b"DLSSD.ColorBeforeFog\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterFog: &[u8; 20] = b"DLSSD.ColorAfterFog\0";
pub const NVSDK_NGX_Parameter_DLSSD_ScreenSpaceSubsurfaceScatteringGuide: &[u8; 43] =
    b"DLSSD.ScreenSpaceSubsurfaceScatteringGuide\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeScreenSpaceSubsurfaceScattering: &[u8; 49] =
    b"DLSSD.ColorBeforeScreenSpaceSubsurfaceScattering\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterScreenSpaceSubsurfaceScattering: &[u8; 48] =
    b"DLSSD.ColorAfterScreenSpaceSubsurfaceScattering\0";
pub const NVSDK_NGX_Parameter_DLSSD_ScreenSpaceRefractionGuide: &[u8; 33] =
    b"DLSSD.ScreenSpaceRefractionGuide\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeScreenSpaceRefraction: &[u8; 39] =
    b"DLSSD.ColorBeforeScreenSpaceRefraction\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterScreenSpaceRefraction: &[u8; 38] =
    b"DLSSD.ColorAfterScreenSpaceRefraction\0";
pub const NVSDK_NGX_Parameter_DLSSD_DepthOfFieldGuide: &[u8; 24] = b"DLSSD.DepthOfFieldGuide\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeDepthOfField: &[u8; 30] =
    b"DLSSD.ColorBeforeDepthOfField\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterDepthOfField: &[u8; 29] =
    b"DLSSD.ColorAfterDepthOfField\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseHitDistance: &[u8; 25] = b"DLSSD.DiffuseHitDistance\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularHitDistance: &[u8; 26] = b"DLSSD.SpecularHitDistance\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseRayDirection: &[u8; 26] = b"DLSSD.DiffuseRayDirection\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularRayDirection: &[u8; 27] =
    b"DLSSD.SpecularRayDirection\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseRayDirectionHitDistance: &[u8; 37] =
    b"DLSSD.DiffuseRayDirectionHitDistance\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularRayDirectionHitDistance: &[u8; 38] =
    b"DLSSD.SpecularRayDirectionHitDistance\0";
pub const NVSDK_NGX_Parameter_DLSSD_Alpha: &[u8; 12] = b"DLSSD.Alpha\0";
pub const NVSDK_NGX_Parameter_DLSSD_OutputAlpha: &[u8; 18] = b"DLSSD.OutputAlpha\0";
pub const NVSDK_NGX_Parameter_DLSSD_Alpha_Subrect_Base_X: &[u8; 27] =
    b"DLSSD.Alpha.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_Alpha_Subrect_Base_Y: &[u8; 27] =
    b"DLSSD.Alpha.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_OutputAlpha_Subrect_Base_X: &[u8; 33] =
    b"DLSSD.OutputAlpha.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_OutputAlpha_Subrect_Base_Y: &[u8; 33] =
    b"DLSSD.OutputAlpha.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ReflectedAlbedo_Subrect_Base_X: &[u8; 37] =
    b"DLSSD.ReflectedAlbedo.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ReflectedAlbedo_Subrect_Base_Y: &[u8; 37] =
    b"DLSSD.ReflectedAlbedo.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeParticles_Subrect_Base_X: &[u8; 42] =
    b"DLSSD.ColorBeforeParticles.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeParticles_Subrect_Base_Y: &[u8; 42] =
    b"DLSSD.ColorBeforeParticles.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterParticles_Subrect_Base_X: &[u8; 41] =
    b"DLSSD.ColorAfterParticles.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterParticles_Subrect_Base_Y: &[u8; 41] =
    b"DLSSD.ColorAfterParticles.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeTransparency_Subrect_Base_X: &[u8; 45] =
    b"DLSSD.ColorBeforeTransparency.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeTransparency_Subrect_Base_Y: &[u8; 45] =
    b"DLSSD.ColorBeforeTransparency.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterTransparency_Subrect_Base_X: &[u8; 44] =
    b"DLSSD.ColorAfterTransparency.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterTransparency_Subrect_Base_Y: &[u8; 44] =
    b"DLSSD.ColorAfterTransparency.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeFog_Subrect_Base_X: &[u8; 36] =
    b"DLSSD.ColorBeforeFog.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeFog_Subrect_Base_Y: &[u8; 36] =
    b"DLSSD.ColorBeforeFog.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterFog_Subrect_Base_X: &[u8; 35] =
    b"DLSSD.ColorAfterFog.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterFog_Subrect_Base_Y: &[u8; 35] =
    b"DLSSD.ColorAfterFog.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ScreenSpaceSubsurfaceScatteringGuide_Subrect_Base_X: &[u8; 58] =
    b"DLSSD.ScreenSpaceSubsurfaceScatteringGuide.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ScreenSpaceSubsurfaceScatteringGuide_Subrect_Base_Y: &[u8; 58] =
    b"DLSSD.ScreenSpaceSubsurfaceScatteringGuide.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeScreenSpaceSubsurfaceScattering_Subrect_Base_X:
    &[u8; 64] = b"DLSSD.ColorBeforeScreenSpaceSubsurfaceScattering.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeScreenSpaceSubsurfaceScattering_Subrect_Base_Y:
    &[u8; 64] = b"DLSSD.ColorBeforeScreenSpaceSubsurfaceScattering.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterScreenSpaceSubsurfaceScattering_Subrect_Base_X:
    &[u8; 63] = b"DLSSD.ColorAfterScreenSpaceSubsurfaceScattering.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterScreenSpaceSubsurfaceScattering_Subrect_Base_Y:
    &[u8; 63] = b"DLSSD.ColorAfterScreenSpaceSubsurfaceScattering.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ScreenSpaceRefractionGuide_Subrect_Base_X: &[u8; 48] =
    b"DLSSD.ScreenSpaceRefractionGuide.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ScreenSpaceRefractionGuide_Subrect_Base_Y: &[u8; 48] =
    b"DLSSD.ScreenSpaceRefractionGuide.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeScreenSpaceRefraction_Subrect_Base_X: &[u8; 54] =
    b"DLSSD.ColorBeforeScreenSpaceRefraction.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeScreenSpaceRefraction_Subrect_Base_Y: &[u8; 54] =
    b"DLSSD.ColorBeforeScreenSpaceRefraction.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterScreenSpaceRefraction_Subrect_Base_X: &[u8; 53] =
    b"DLSSD.ColorAfterScreenSpaceRefraction.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterScreenSpaceRefraction_Subrect_Base_Y: &[u8; 53] =
    b"DLSSD.ColorAfterScreenSpaceRefraction.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_DepthOfFieldGuide_Subrect_Base_X: &[u8; 39] =
    b"DLSSD.DepthOfFieldGuide.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_DepthOfFieldGuide_Subrect_Base_Y: &[u8; 39] =
    b"DLSSD.DepthOfFieldGuide.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeDepthOfField_Subrect_Base_X: &[u8; 45] =
    b"DLSSD.ColorBeforeDepthOfField.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorBeforeDepthOfField_Subrect_Base_Y: &[u8; 45] =
    b"DLSSD.ColorBeforeDepthOfField.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterDepthOfField_Subrect_Base_X: &[u8; 44] =
    b"DLSSD.ColorAfterDepthOfField.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_ColorAfterDepthOfField_Subrect_Base_Y: &[u8; 44] =
    b"DLSSD.ColorAfterDepthOfField.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseHitDistance_Subrect_Base_X: &[u8; 40] =
    b"DLSSD.DiffuseHitDistance.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseHitDistance_Subrect_Base_Y: &[u8; 40] =
    b"DLSSD.DiffuseHitDistance.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularHitDistance_Subrect_Base_X: &[u8; 41] =
    b"DLSSD.SpecularHitDistance.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularHitDistance_Subrect_Base_Y: &[u8; 41] =
    b"DLSSD.SpecularHitDistance.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseRayDirection_Subrect_Base_X: &[u8; 41] =
    b"DLSSD.DiffuseRayDirection.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseRayDirection_Subrect_Base_Y: &[u8; 41] =
    b"DLSSD.DiffuseRayDirection.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularRayDirection_Subrect_Base_X: &[u8; 42] =
    b"DLSSD.SpecularRayDirection.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularRayDirection_Subrect_Base_Y: &[u8; 42] =
    b"DLSSD.SpecularRayDirection.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseRayDirectionHitDistance_Subrect_Base_X: &[u8; 52] =
    b"DLSSD.DiffuseRayDirectionHitDistance.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_DiffuseRayDirectionHitDistance_Subrect_Base_Y: &[u8; 52] =
    b"DLSSD.DiffuseRayDirectionHitDistance.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularRayDirectionHitDistance_Subrect_Base_X: &[u8; 53] =
    b"DLSSD.SpecularRayDirectionHitDistance.Subrect.Base.X\0";
pub const NVSDK_NGX_Parameter_DLSSD_SpecularRayDirectionHitDistance_Subrect_Base_Y: &[u8; 53] =
    b"DLSSD.SpecularRayDirectionHitDistance.Subrect.Base.Y\0";
pub const NVSDK_NGX_Parameter_SuperSamplingDenoising_Available: &[u8; 33] =
    b"SuperSamplingDenoising.Available\0";
pub const NVSDK_NGX_Parameter_SuperSamplingDenoising_NeedsUpdatedDriver: &[u8; 42] =
    b"SuperSamplingDenoising.NeedsUpdatedDriver\0";
pub const NVSDK_NGX_Parameter_SuperSamplingDenoising_MinDriverVersionMajor: &[u8; 45] =
    b"SuperSamplingDenoising.MinDriverVersionMajor\0";
pub const NVSDK_NGX_Parameter_SuperSamplingDenoising_MinDriverVersionMinor: &[u8; 45] =
    b"SuperSamplingDenoising.MinDriverVersionMinor\0";
pub const NVSDK_NGX_Parameter_SuperSamplingDenoising_FeatureInitResult: &[u8; 41] =
    b"SuperSamplingDenoising.FeatureInitResult\0";
pub const NVSDK_NGX_Parameter_DLSSDOptimalSettingsCallback: &[u8; 29] =
    b"DLSSDOptimalSettingsCallback\0";
pub const NVSDK_NGX_Parameter_DLSSDGetStatsCallback: &[u8; 22] = b"DLSSDGetStatsCallback\0";
pub const NVSDK_NGX_Parameter_RayReconstruction_Hint_Render_Preset_DLAA: &[u8; 42] =
    b"RayReconstruction.Hint.Render.Preset.DLAA\0";
pub const NVSDK_NGX_Parameter_RayReconstruction_Hint_Render_Preset_Quality: &[u8; 45] =
    b"RayReconstruction.Hint.Render.Preset.Quality\0";
pub const NVSDK_NGX_Parameter_RayReconstruction_Hint_Render_Preset_Balanced: &[u8; 46] =
    b"RayReconstruction.Hint.Render.Preset.Balanced\0";
pub const NVSDK_NGX_Parameter_RayReconstruction_Hint_Render_Preset_Performance: &[u8; 49] =
    b"RayReconstruction.Hint.Render.Preset.Performance\0";
pub const NVSDK_NGX_Parameter_RayReconstruction_Hint_Render_Preset_UltraPerformance: &[u8; 54] =
    b"RayReconstruction.Hint.Render.Preset.UltraPerformance\0";
pub const NVSDK_NGX_Parameter_RayReconstruction_Hint_Render_Preset_UltraQuality: &[u8; 50] =
    b"RayReconstruction.Hint.Render.Preset.UltraQuality\0";
impl NVSDK_NGX_DLSS_Hint_Render_Preset {
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_Default: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(0);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_A: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(1);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_B: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(2);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_C: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(3);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_D: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(4);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_E: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(5);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_F: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(6);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_G: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(7);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_H_Reserved: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(8);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_I_Reserved: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(9);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_J: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(10);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_K: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(11);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_L: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(12);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_M: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(13);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_N: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(14);
    pub const NVSDK_NGX_DLSS_Hint_Render_Preset_O: NVSDK_NGX_DLSS_Hint_Render_Preset =
        NVSDK_NGX_DLSS_Hint_Render_Preset(15);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_DLSS_Hint_Render_Preset(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_FeatureCommonInfo_Internal {
    _unused: [u8; 0],
}
impl NVSDK_NGX_Version {
    pub const NVSDK_NGX_Version_API: NVSDK_NGX_Version = NVSDK_NGX_Version(21);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Version(pub ::std::os::raw::c_int);
impl NVSDK_NGX_Result {
    pub const NVSDK_NGX_Result_Success: NVSDK_NGX_Result = NVSDK_NGX_Result(1);
    pub const NVSDK_NGX_Result_Fail: NVSDK_NGX_Result = NVSDK_NGX_Result(-1160773632);
    pub const NVSDK_NGX_Result_FAIL_FeatureNotSupported: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773631);
    pub const NVSDK_NGX_Result_FAIL_PlatformError: NVSDK_NGX_Result = NVSDK_NGX_Result(-1160773630);
    pub const NVSDK_NGX_Result_FAIL_FeatureAlreadyExists: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773629);
    pub const NVSDK_NGX_Result_FAIL_FeatureNotFound: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773628);
    pub const NVSDK_NGX_Result_FAIL_InvalidParameter: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773627);
    pub const NVSDK_NGX_Result_FAIL_ScratchBufferTooSmall: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773626);
    pub const NVSDK_NGX_Result_FAIL_NotInitialized: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773625);
    pub const NVSDK_NGX_Result_FAIL_UnsupportedInputFormat: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773624);
    pub const NVSDK_NGX_Result_FAIL_RWFlagMissing: NVSDK_NGX_Result = NVSDK_NGX_Result(-1160773623);
    pub const NVSDK_NGX_Result_FAIL_MissingInput: NVSDK_NGX_Result = NVSDK_NGX_Result(-1160773622);
    pub const NVSDK_NGX_Result_FAIL_UnableToInitializeFeature: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773621);
    pub const NVSDK_NGX_Result_FAIL_OutOfDate: NVSDK_NGX_Result = NVSDK_NGX_Result(-1160773620);
    pub const NVSDK_NGX_Result_FAIL_OutOfGPUMemory: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773619);
    pub const NVSDK_NGX_Result_FAIL_UnsupportedFormat: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773618);
    pub const NVSDK_NGX_Result_FAIL_UnableToWriteToAppDataPath: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773617);
    pub const NVSDK_NGX_Result_FAIL_UnsupportedParameter: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773616);
    pub const NVSDK_NGX_Result_FAIL_Denied: NVSDK_NGX_Result = NVSDK_NGX_Result(-1160773615);
    pub const NVSDK_NGX_Result_FAIL_NotImplemented: NVSDK_NGX_Result =
        NVSDK_NGX_Result(-1160773614);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Result(pub ::std::os::raw::c_int);
impl NVSDK_NGX_Feature {
    pub const NVSDK_NGX_Feature_Reserved0: NVSDK_NGX_Feature = NVSDK_NGX_Feature(0);
    pub const NVSDK_NGX_Feature_SuperSampling: NVSDK_NGX_Feature = NVSDK_NGX_Feature(1);
    pub const NVSDK_NGX_Feature_InPainting: NVSDK_NGX_Feature = NVSDK_NGX_Feature(2);
    pub const NVSDK_NGX_Feature_ImageSuperResolution: NVSDK_NGX_Feature = NVSDK_NGX_Feature(3);
    pub const NVSDK_NGX_Feature_SlowMotion: NVSDK_NGX_Feature = NVSDK_NGX_Feature(4);
    pub const NVSDK_NGX_Feature_VideoSuperResolution: NVSDK_NGX_Feature = NVSDK_NGX_Feature(5);
    pub const NVSDK_NGX_Feature_Reserved1: NVSDK_NGX_Feature = NVSDK_NGX_Feature(6);
    pub const NVSDK_NGX_Feature_Reserved2: NVSDK_NGX_Feature = NVSDK_NGX_Feature(7);
    pub const NVSDK_NGX_Feature_Reserved3: NVSDK_NGX_Feature = NVSDK_NGX_Feature(8);
    pub const NVSDK_NGX_Feature_ImageSignalProcessing: NVSDK_NGX_Feature = NVSDK_NGX_Feature(9);
    pub const NVSDK_NGX_Feature_DeepResolve: NVSDK_NGX_Feature = NVSDK_NGX_Feature(10);
    pub const NVSDK_NGX_Feature_FrameGeneration: NVSDK_NGX_Feature = NVSDK_NGX_Feature(11);
    pub const NVSDK_NGX_Feature_DeepDVC: NVSDK_NGX_Feature = NVSDK_NGX_Feature(12);
    pub const NVSDK_NGX_Feature_RayReconstruction: NVSDK_NGX_Feature = NVSDK_NGX_Feature(13);
    pub const NVSDK_NGX_Feature_Reserved14: NVSDK_NGX_Feature = NVSDK_NGX_Feature(14);
    pub const NVSDK_NGX_Feature_Reserved15: NVSDK_NGX_Feature = NVSDK_NGX_Feature(15);
    pub const NVSDK_NGX_Feature_Reserved16: NVSDK_NGX_Feature = NVSDK_NGX_Feature(16);
    pub const NVSDK_NGX_Feature_Count: NVSDK_NGX_Feature = NVSDK_NGX_Feature(17);
    pub const NVSDK_NGX_Feature_Reserved_SDK: NVSDK_NGX_Feature = NVSDK_NGX_Feature(32764);
    pub const NVSDK_NGX_Feature_Reserved_Core: NVSDK_NGX_Feature = NVSDK_NGX_Feature(32765);
    pub const NVSDK_NGX_Feature_Reserved_Unknown: NVSDK_NGX_Feature = NVSDK_NGX_Feature(32766);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Feature(pub ::std::os::raw::c_int);
impl NVSDK_NGX_Buffer_Format {
    pub const NVSDK_NGX_Buffer_Format_Unknown: NVSDK_NGX_Buffer_Format = NVSDK_NGX_Buffer_Format(0);
    pub const NVSDK_NGX_Buffer_Format_RGB8UI: NVSDK_NGX_Buffer_Format = NVSDK_NGX_Buffer_Format(1);
    pub const NVSDK_NGX_Buffer_Format_RGB16F: NVSDK_NGX_Buffer_Format = NVSDK_NGX_Buffer_Format(2);
    pub const NVSDK_NGX_Buffer_Format_RGB32F: NVSDK_NGX_Buffer_Format = NVSDK_NGX_Buffer_Format(3);
    pub const NVSDK_NGX_Buffer_Format_RGBA8UI: NVSDK_NGX_Buffer_Format = NVSDK_NGX_Buffer_Format(4);
    pub const NVSDK_NGX_Buffer_Format_RGBA16F: NVSDK_NGX_Buffer_Format = NVSDK_NGX_Buffer_Format(5);
    pub const NVSDK_NGX_Buffer_Format_RGBA32F: NVSDK_NGX_Buffer_Format = NVSDK_NGX_Buffer_Format(6);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Buffer_Format(pub ::std::os::raw::c_int);
impl NVSDK_NGX_PerfQuality_Value {
    pub const NVSDK_NGX_PerfQuality_Value_MaxPerf: NVSDK_NGX_PerfQuality_Value =
        NVSDK_NGX_PerfQuality_Value(0);
    pub const NVSDK_NGX_PerfQuality_Value_Balanced: NVSDK_NGX_PerfQuality_Value =
        NVSDK_NGX_PerfQuality_Value(1);
    pub const NVSDK_NGX_PerfQuality_Value_MaxQuality: NVSDK_NGX_PerfQuality_Value =
        NVSDK_NGX_PerfQuality_Value(2);
    pub const NVSDK_NGX_PerfQuality_Value_UltraPerformance: NVSDK_NGX_PerfQuality_Value =
        NVSDK_NGX_PerfQuality_Value(3);
    pub const NVSDK_NGX_PerfQuality_Value_UltraQuality: NVSDK_NGX_PerfQuality_Value =
        NVSDK_NGX_PerfQuality_Value(4);
    pub const NVSDK_NGX_PerfQuality_Value_DLAA: NVSDK_NGX_PerfQuality_Value =
        NVSDK_NGX_PerfQuality_Value(5);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_PerfQuality_Value(pub ::std::os::raw::c_int);
impl NVSDK_NGX_RTX_Value {
    pub const NVSDK_NGX_RTX_Value_Off: NVSDK_NGX_RTX_Value = NVSDK_NGX_RTX_Value(0);
    pub const NVSDK_NGX_RTX_Value_On: NVSDK_NGX_RTX_Value = NVSDK_NGX_RTX_Value(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_RTX_Value(pub ::std::os::raw::c_int);
impl NVSDK_NGX_DLSS_Mode {
    pub const NVSDK_NGX_DLSS_Mode_Off: NVSDK_NGX_DLSS_Mode = NVSDK_NGX_DLSS_Mode(0);
    pub const NVSDK_NGX_DLSS_Mode_DLSS_DLISP: NVSDK_NGX_DLSS_Mode = NVSDK_NGX_DLSS_Mode(1);
    pub const NVSDK_NGX_DLSS_Mode_DLISP_Only: NVSDK_NGX_DLSS_Mode = NVSDK_NGX_DLSS_Mode(2);
    pub const NVSDK_NGX_DLSS_Mode_DLSS: NVSDK_NGX_DLSS_Mode = NVSDK_NGX_DLSS_Mode(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_DLSS_Mode(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVSDK_NGX_Handle {
    pub Id: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_Handle() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_Handle> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_Handle>(),
        4usize,
        "Size of NVSDK_NGX_Handle"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_Handle>(),
        4usize,
        "Alignment of NVSDK_NGX_Handle"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Id) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_Handle::Id"
    );
}
impl NVSDK_NGX_GPU_Arch {
    pub const NVSDK_NGX_GPU_Arch_NotSupported: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(0);
    pub const NVSDK_NGX_GPU_Arch_Volta: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(320);
    pub const NVSDK_NGX_GPU_Arch_Turing: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(352);
    pub const NVSDK_NGX_GPU_Arch_Ampere: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(368);
    pub const NVSDK_NGX_GPU_Arch_Ada: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(400);
    pub const NVSDK_NGX_GPU_Arch_Hopper: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(384);
    pub const NVSDK_NGX_GPU_Arch_Blackwell: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(416);
    pub const NVSDK_NGX_GPU_Arch_Blackwell2: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(432);
    pub const NVSDK_NGX_GPU_Arch_Unknown: NVSDK_NGX_GPU_Arch = NVSDK_NGX_GPU_Arch(134217727);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_GPU_Arch(pub ::std::os::raw::c_int);
impl NVSDK_NGX_DLSS_Feature_Flags {
    pub const NVSDK_NGX_DLSS_Feature_Flags_IsInvalid: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(-2147483648);
    pub const NVSDK_NGX_DLSS_Feature_Flags_None: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(0);
    pub const NVSDK_NGX_DLSS_Feature_Flags_IsHDR: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(1);
    pub const NVSDK_NGX_DLSS_Feature_Flags_MVLowRes: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(2);
    pub const NVSDK_NGX_DLSS_Feature_Flags_MVJittered: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(4);
    pub const NVSDK_NGX_DLSS_Feature_Flags_DepthInverted: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(8);
    pub const NVSDK_NGX_DLSS_Feature_Flags_Reserved_0: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(16);
    pub const NVSDK_NGX_DLSS_Feature_Flags_DoSharpening: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(32);
    pub const NVSDK_NGX_DLSS_Feature_Flags_AutoExposure: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(64);
    pub const NVSDK_NGX_DLSS_Feature_Flags_AlphaUpscaling: NVSDK_NGX_DLSS_Feature_Flags =
        NVSDK_NGX_DLSS_Feature_Flags(128);
}
impl ::std::ops::BitOr<NVSDK_NGX_DLSS_Feature_Flags> for NVSDK_NGX_DLSS_Feature_Flags {
    type Output = Self;
    #[inline]
    fn bitor(self, other: Self) -> Self {
        NVSDK_NGX_DLSS_Feature_Flags(self.0 | other.0)
    }
}
impl ::std::ops::BitOrAssign for NVSDK_NGX_DLSS_Feature_Flags {
    #[inline]
    fn bitor_assign(&mut self, rhs: NVSDK_NGX_DLSS_Feature_Flags) {
        self.0 |= rhs.0;
    }
}
impl ::std::ops::BitAnd<NVSDK_NGX_DLSS_Feature_Flags> for NVSDK_NGX_DLSS_Feature_Flags {
    type Output = Self;
    #[inline]
    fn bitand(self, other: Self) -> Self {
        NVSDK_NGX_DLSS_Feature_Flags(self.0 & other.0)
    }
}
impl ::std::ops::BitAndAssign for NVSDK_NGX_DLSS_Feature_Flags {
    #[inline]
    fn bitand_assign(&mut self, rhs: NVSDK_NGX_DLSS_Feature_Flags) {
        self.0 &= rhs.0;
    }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_DLSS_Feature_Flags(pub ::std::os::raw::c_int);
impl NVSDK_NGX_ToneMapperType {
    pub const NVSDK_NGX_TONEMAPPER_STRING: NVSDK_NGX_ToneMapperType = NVSDK_NGX_ToneMapperType(0);
    pub const NVSDK_NGX_TONEMAPPER_REINHARD: NVSDK_NGX_ToneMapperType = NVSDK_NGX_ToneMapperType(1);
    pub const NVSDK_NGX_TONEMAPPER_ONEOVERLUMA: NVSDK_NGX_ToneMapperType =
        NVSDK_NGX_ToneMapperType(2);
    pub const NVSDK_NGX_TONEMAPPER_ACES: NVSDK_NGX_ToneMapperType = NVSDK_NGX_ToneMapperType(3);
    pub const NVSDK_NGX_TONEMAPPERTYPE_NUM: NVSDK_NGX_ToneMapperType = NVSDK_NGX_ToneMapperType(4);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_ToneMapperType(pub ::std::os::raw::c_int);
impl NVSDK_NGX_GBufferType {
    pub const NVSDK_NGX_GBUFFER_ALBEDO: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(0);
    pub const NVSDK_NGX_GBUFFER_ROUGHNESS: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(1);
    pub const NVSDK_NGX_GBUFFER_METALLIC: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(2);
    pub const NVSDK_NGX_GBUFFER_SPECULAR: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(3);
    pub const NVSDK_NGX_GBUFFER_SUBSURFACE: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(4);
    pub const NVSDK_NGX_GBUFFER_NORMALS: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(5);
    pub const NVSDK_NGX_GBUFFER_SHADINGMODELID: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(6);
    pub const NVSDK_NGX_GBUFFER_MATERIALID: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(7);
    pub const NVSDK_NGX_GBUFFER_SPECULAR_ALBEDO: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(8);
    pub const NVSDK_NGX_GBUFFER_INDIRECT_ALBEDO: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(9);
    pub const NVSDK_NGX_GBUFFER_SPECULAR_MVEC: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(10);
    pub const NVSDK_NGX_GBUFFER_DISOCCL_MASK: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(11);
    pub const NVSDK_NGX_GBUFFER_EMISSIVE: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(12);
    pub const NVSDK_NGX_GBUFFERTYPE_NUM: NVSDK_NGX_GBufferType = NVSDK_NGX_GBufferType(16);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_GBufferType(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVSDK_NGX_Coordinates {
    pub X: ::std::os::raw::c_uint,
    pub Y: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_Coordinates() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_Coordinates> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_Coordinates>(),
        8usize,
        "Size of NVSDK_NGX_Coordinates"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_Coordinates>(),
        4usize,
        "Alignment of NVSDK_NGX_Coordinates"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).X) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_Coordinates::X"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Y) as usize - ptr as usize },
        4usize,
        "Offset of field: NVSDK_NGX_Coordinates::Y"
    );
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVSDK_NGX_Dimensions {
    pub Width: ::std::os::raw::c_uint,
    pub Height: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_Dimensions() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_Dimensions> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_Dimensions>(),
        8usize,
        "Size of NVSDK_NGX_Dimensions"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_Dimensions>(),
        4usize,
        "Alignment of NVSDK_NGX_Dimensions"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Width) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_Dimensions::Width"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Height) as usize - ptr as usize },
        4usize,
        "Offset of field: NVSDK_NGX_Dimensions::Height"
    );
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct NVSDK_NGX_PrecisionInfo {
    pub IsLowPrecision: ::std::os::raw::c_uint,
    pub Bias: f32,
    pub Scale: f32,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_PrecisionInfo() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_PrecisionInfo> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_PrecisionInfo>(),
        12usize,
        "Size of NVSDK_NGX_PrecisionInfo"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_PrecisionInfo>(),
        4usize,
        "Alignment of NVSDK_NGX_PrecisionInfo"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IsLowPrecision) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_PrecisionInfo::IsLowPrecision"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Bias) as usize - ptr as usize },
        4usize,
        "Offset of field: NVSDK_NGX_PrecisionInfo::Bias"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Scale) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_PrecisionInfo::Scale"
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_PathListInfo {
    pub Path: *const *const wchar_t,
    pub Length: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_PathListInfo() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_PathListInfo> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_PathListInfo>(),
        16usize,
        "Size of NVSDK_NGX_PathListInfo"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_PathListInfo>(),
        8usize,
        "Alignment of NVSDK_NGX_PathListInfo"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Path) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_PathListInfo::Path"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Length) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_PathListInfo::Length"
    );
}
impl Default for NVSDK_NGX_PathListInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl NVSDK_NGX_Logging_Level {
    pub const NVSDK_NGX_LOGGING_LEVEL_OFF: NVSDK_NGX_Logging_Level = NVSDK_NGX_Logging_Level(0);
    pub const NVSDK_NGX_LOGGING_LEVEL_ON: NVSDK_NGX_Logging_Level = NVSDK_NGX_Logging_Level(1);
    pub const NVSDK_NGX_LOGGING_LEVEL_VERBOSE: NVSDK_NGX_Logging_Level = NVSDK_NGX_Logging_Level(2);
    pub const NVSDK_NGX_LOGGING_LEVEL_NUM: NVSDK_NGX_Logging_Level = NVSDK_NGX_Logging_Level(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Logging_Level(pub ::std::os::raw::c_int);
pub type NVSDK_NGX_AppLogCallback = ::std::option::Option<
    unsafe extern "C" fn(
        message: *const ::std::os::raw::c_char,
        loggingLevel: NVSDK_NGX_Logging_Level,
        sourceComponent: NVSDK_NGX_Feature,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_LoggingInfo {
    pub LoggingCallback: NVSDK_NGX_AppLogCallback,
    pub MinimumLoggingLevel: NVSDK_NGX_Logging_Level,
    pub DisableOtherLoggingSinks: bool,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_LoggingInfo() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_LoggingInfo> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_LoggingInfo>(),
        16usize,
        "Size of NVSDK_NGX_LoggingInfo"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_LoggingInfo>(),
        8usize,
        "Alignment of NVSDK_NGX_LoggingInfo"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).LoggingCallback) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_LoggingInfo::LoggingCallback"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MinimumLoggingLevel) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_LoggingInfo::MinimumLoggingLevel"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).DisableOtherLoggingSinks) as usize - ptr as usize },
        12usize,
        "Offset of field: NVSDK_NGX_LoggingInfo::DisableOtherLoggingSinks"
    );
}
impl Default for NVSDK_NGX_LoggingInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_FeatureCommonInfo {
    pub PathListInfo: NVSDK_NGX_PathListInfo,
    pub InternalData: *mut NVSDK_NGX_FeatureCommonInfo_Internal,
    pub LoggingInfo: NVSDK_NGX_LoggingInfo,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_FeatureCommonInfo() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_FeatureCommonInfo> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_FeatureCommonInfo>(),
        40usize,
        "Size of NVSDK_NGX_FeatureCommonInfo"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_FeatureCommonInfo>(),
        8usize,
        "Alignment of NVSDK_NGX_FeatureCommonInfo"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).PathListInfo) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_FeatureCommonInfo::PathListInfo"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InternalData) as usize - ptr as usize },
        16usize,
        "Offset of field: NVSDK_NGX_FeatureCommonInfo::InternalData"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).LoggingInfo) as usize - ptr as usize },
        24usize,
        "Offset of field: NVSDK_NGX_FeatureCommonInfo::LoggingInfo"
    );
}
impl Default for NVSDK_NGX_FeatureCommonInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl NVSDK_NGX_Opt_Level {
    pub const NVSDK_NGX_OPT_LEVEL_UNDEFINED: NVSDK_NGX_Opt_Level = NVSDK_NGX_Opt_Level(0);
    pub const NVSDK_NGX_OPT_LEVEL_DEBUG: NVSDK_NGX_Opt_Level = NVSDK_NGX_Opt_Level(20);
    pub const NVSDK_NGX_OPT_LEVEL_DEVELOP: NVSDK_NGX_Opt_Level = NVSDK_NGX_Opt_Level(30);
    pub const NVSDK_NGX_OPT_LEVEL_RELEASE: NVSDK_NGX_Opt_Level = NVSDK_NGX_Opt_Level(40);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Opt_Level(pub ::std::os::raw::c_int);
impl NVSDK_NGX_EngineType {
    pub const NVSDK_NGX_ENGINE_TYPE_CUSTOM: NVSDK_NGX_EngineType = NVSDK_NGX_EngineType(0);
    pub const NVSDK_NGX_ENGINE_TYPE_UNREAL: NVSDK_NGX_EngineType = NVSDK_NGX_EngineType(1);
    pub const NVSDK_NGX_ENGINE_TYPE_UNITY: NVSDK_NGX_EngineType = NVSDK_NGX_EngineType(2);
    pub const NVSDK_NGX_ENGINE_TYPE_OMNIVERSE: NVSDK_NGX_EngineType = NVSDK_NGX_EngineType(3);
    pub const NVSDK_NGX_ENGINE_COUNT: NVSDK_NGX_EngineType = NVSDK_NGX_EngineType(4);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_EngineType(pub ::std::os::raw::c_int);
impl NVSDK_NGX_Feature_Support_Result {
    pub const NVSDK_NGX_FeatureSupportResult_Supported: NVSDK_NGX_Feature_Support_Result =
        NVSDK_NGX_Feature_Support_Result(0);
    pub const NVSDK_NGX_FeatureSupportResult_CheckNotPresent: NVSDK_NGX_Feature_Support_Result =
        NVSDK_NGX_Feature_Support_Result(1);
    pub const NVSDK_NGX_FeatureSupportResult_DriverVersionUnsupported:
        NVSDK_NGX_Feature_Support_Result = NVSDK_NGX_Feature_Support_Result(2);
    pub const NVSDK_NGX_FeatureSupportResult_AdapterUnsupported: NVSDK_NGX_Feature_Support_Result =
        NVSDK_NGX_Feature_Support_Result(4);
    pub const NVSDK_NGX_FeatureSupportResult_OSVersionBelowMinimumSupported:
        NVSDK_NGX_Feature_Support_Result = NVSDK_NGX_Feature_Support_Result(8);
    pub const NVSDK_NGX_FeatureSupportResult_NotImplemented: NVSDK_NGX_Feature_Support_Result =
        NVSDK_NGX_Feature_Support_Result(16);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Feature_Support_Result(pub ::std::os::raw::c_int);
impl NVSDK_NGX_Application_Identifier_Type {
    pub const NVSDK_NGX_Application_Identifier_Type_Application_Id:
        NVSDK_NGX_Application_Identifier_Type = NVSDK_NGX_Application_Identifier_Type(0);
    pub const NVSDK_NGX_Application_Identifier_Type_Project_Id:
        NVSDK_NGX_Application_Identifier_Type = NVSDK_NGX_Application_Identifier_Type(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_Application_Identifier_Type(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_ProjectIdDescription {
    pub ProjectId: *const ::std::os::raw::c_char,
    pub EngineType: NVSDK_NGX_EngineType,
    pub EngineVersion: *const ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_ProjectIdDescription() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_ProjectIdDescription> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_ProjectIdDescription>(),
        24usize,
        "Size of NVSDK_NGX_ProjectIdDescription"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_ProjectIdDescription>(),
        8usize,
        "Alignment of NVSDK_NGX_ProjectIdDescription"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ProjectId) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_ProjectIdDescription::ProjectId"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).EngineType) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_ProjectIdDescription::EngineType"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).EngineVersion) as usize - ptr as usize },
        16usize,
        "Offset of field: NVSDK_NGX_ProjectIdDescription::EngineVersion"
    );
}
impl Default for NVSDK_NGX_ProjectIdDescription {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct NVSDK_NGX_Application_Identifier {
    pub IdentifierType: NVSDK_NGX_Application_Identifier_Type,
    pub v: v,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union v {
    pub ProjectDesc: NVSDK_NGX_ProjectIdDescription,
    pub ApplicationId: ::std::os::raw::c_ulonglong,
}
#[test]
fn bindgen_test_layout_v() {
    const UNINIT: ::std::mem::MaybeUninit<v> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(::std::mem::size_of::<v>(), 24usize, "Size of v");
    assert_eq!(::std::mem::align_of::<v>(), 8usize, "Alignment of v");
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ProjectDesc) as usize - ptr as usize },
        0usize,
        "Offset of field: v::ProjectDesc"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ApplicationId) as usize - ptr as usize },
        0usize,
        "Offset of field: v::ApplicationId"
    );
}
impl Default for v {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl ::std::fmt::Debug for v {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "v {{ union }}")
    }
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_Application_Identifier() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_Application_Identifier> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_Application_Identifier>(),
        32usize,
        "Size of NVSDK_NGX_Application_Identifier"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_Application_Identifier>(),
        8usize,
        "Alignment of NVSDK_NGX_Application_Identifier"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).IdentifierType) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_Application_Identifier::IdentifierType"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).v) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_Application_Identifier::v"
    );
}
impl Default for NVSDK_NGX_Application_Identifier {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl ::std::fmt::Debug for NVSDK_NGX_Application_Identifier {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(
            f,
            "NVSDK_NGX_Application_Identifier {{ IdentifierType: {:?}, v: {:?} }}",
            self.IdentifierType, self.v
        )
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct NVSDK_NGX_FeatureDiscoveryInfo {
    pub SDKVersion: NVSDK_NGX_Version,
    pub FeatureID: NVSDK_NGX_Feature,
    pub Identifier: NVSDK_NGX_Application_Identifier,
    pub ApplicationDataPath: *const wchar_t,
    pub FeatureInfo: *const NVSDK_NGX_FeatureCommonInfo,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_FeatureDiscoveryInfo() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_FeatureDiscoveryInfo> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_FeatureDiscoveryInfo>(),
        56usize,
        "Size of NVSDK_NGX_FeatureDiscoveryInfo"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_FeatureDiscoveryInfo>(),
        8usize,
        "Alignment of NVSDK_NGX_FeatureDiscoveryInfo"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).SDKVersion) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_FeatureDiscoveryInfo::SDKVersion"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).FeatureID) as usize - ptr as usize },
        4usize,
        "Offset of field: NVSDK_NGX_FeatureDiscoveryInfo::FeatureID"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Identifier) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_FeatureDiscoveryInfo::Identifier"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ApplicationDataPath) as usize - ptr as usize },
        40usize,
        "Offset of field: NVSDK_NGX_FeatureDiscoveryInfo::ApplicationDataPath"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).FeatureInfo) as usize - ptr as usize },
        48usize,
        "Offset of field: NVSDK_NGX_FeatureDiscoveryInfo::FeatureInfo"
    );
}
impl Default for NVSDK_NGX_FeatureDiscoveryInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl ::std::fmt::Debug for NVSDK_NGX_FeatureDiscoveryInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write ! (f , "NVSDK_NGX_FeatureDiscoveryInfo {{ SDKVersion: {:?}, FeatureID: {:?}, Identifier: {:?}, ApplicationDataPath: {:?}, FeatureInfo: {:?} }}" , self . SDKVersion , self . FeatureID , self . Identifier , self . ApplicationDataPath , self . FeatureInfo)
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_FeatureRequirement {
    pub FeatureSupported: NVSDK_NGX_Feature_Support_Result,
    pub MinHWArchitecture: ::std::os::raw::c_uint,
    pub MinOSVersion: [::std::os::raw::c_char; 255usize],
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_FeatureRequirement() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_FeatureRequirement> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_FeatureRequirement>(),
        264usize,
        "Size of NVSDK_NGX_FeatureRequirement"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_FeatureRequirement>(),
        4usize,
        "Alignment of NVSDK_NGX_FeatureRequirement"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).FeatureSupported) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_FeatureRequirement::FeatureSupported"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MinHWArchitecture) as usize - ptr as usize },
        4usize,
        "Offset of field: NVSDK_NGX_FeatureRequirement::MinHWArchitecture"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MinOSVersion) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_FeatureRequirement::MinOSVersion"
    );
}
impl Default for NVSDK_NGX_FeatureRequirement {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_Feature_Create_Params {
    pub InWidth: ::std::os::raw::c_uint,
    pub InHeight: ::std::os::raw::c_uint,
    pub InTargetWidth: ::std::os::raw::c_uint,
    pub InTargetHeight: ::std::os::raw::c_uint,
    #[doc = " OPTIONAL"]
    pub InPerfQualityValue: NVSDK_NGX_PerfQuality_Value,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_Feature_Create_Params() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_Feature_Create_Params> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_Feature_Create_Params>(),
        20usize,
        "Size of NVSDK_NGX_Feature_Create_Params"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_Feature_Create_Params>(),
        4usize,
        "Alignment of NVSDK_NGX_Feature_Create_Params"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InWidth) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_Feature_Create_Params::InWidth"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InHeight) as usize - ptr as usize },
        4usize,
        "Offset of field: NVSDK_NGX_Feature_Create_Params::InHeight"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InTargetWidth) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_Feature_Create_Params::InTargetWidth"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InTargetHeight) as usize - ptr as usize },
        12usize,
        "Offset of field: NVSDK_NGX_Feature_Create_Params::InTargetHeight"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InPerfQualityValue) as usize - ptr as usize },
        16usize,
        "Offset of field: NVSDK_NGX_Feature_Create_Params::InPerfQualityValue"
    );
}
impl Default for NVSDK_NGX_Feature_Create_Params {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_DLSS_Create_Params {
    pub Feature: NVSDK_NGX_Feature_Create_Params,
    #[doc = " OPTIONAL"]
    pub InFeatureCreateFlags: ::std::os::raw::c_int,
    pub InEnableOutputSubrects: bool,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_DLSS_Create_Params() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_DLSS_Create_Params> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_DLSS_Create_Params>(),
        28usize,
        "Size of NVSDK_NGX_DLSS_Create_Params"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_DLSS_Create_Params>(),
        4usize,
        "Alignment of NVSDK_NGX_DLSS_Create_Params"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Feature) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_DLSS_Create_Params::Feature"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InFeatureCreateFlags) as usize - ptr as usize },
        20usize,
        "Offset of field: NVSDK_NGX_DLSS_Create_Params::InFeatureCreateFlags"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InEnableOutputSubrects) as usize - ptr as usize },
        24usize,
        "Offset of field: NVSDK_NGX_DLSS_Create_Params::InEnableOutputSubrects"
    );
}
impl Default for NVSDK_NGX_DLSS_Create_Params {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_DLDenoise_Create_Params {
    pub Feature: NVSDK_NGX_Feature_Create_Params,
    #[doc = " OPTIONAL"]
    pub InFeatureCreateFlags: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_DLDenoise_Create_Params() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_DLDenoise_Create_Params> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_DLDenoise_Create_Params>(),
        24usize,
        "Size of NVSDK_NGX_DLDenoise_Create_Params"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_DLDenoise_Create_Params>(),
        4usize,
        "Alignment of NVSDK_NGX_DLDenoise_Create_Params"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).Feature) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_DLDenoise_Create_Params::Feature"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InFeatureCreateFlags) as usize - ptr as usize },
        20usize,
        "Offset of field: NVSDK_NGX_DLDenoise_Create_Params::InFeatureCreateFlags"
    );
}
impl Default for NVSDK_NGX_DLDenoise_Create_Params {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_Parameter {
    _unused: [u8; 0],
}
pub type PFN_NVSDK_NGX_Parameter_SetULL = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_ulonglong,
    ),
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetULL(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_ulonglong,
    );
}
pub type PFN_NVSDK_NGX_Parameter_SetF = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f32,
    ),
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetF(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f32,
    );
}
pub type PFN_NVSDK_NGX_Parameter_SetD = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f64,
    ),
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetD(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: f64,
    );
}
pub type PFN_NVSDK_NGX_Parameter_SetUI = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_uint,
    ),
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetUI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_uint,
    );
}
pub type PFN_NVSDK_NGX_Parameter_SetI = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_int,
    ),
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: ::std::os::raw::c_int,
    );
}
pub type PFN_NVSDK_NGX_Parameter_SetVoidPointer = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: *mut ::std::os::raw::c_void,
    ),
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_SetVoidPointer(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        InValue: *mut ::std::os::raw::c_void,
    );
}
pub type PFN_NVSDK_NGX_Parameter_GetULL = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_ulonglong,
    ) -> NVSDK_NGX_Result,
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetULL(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_ulonglong,
    ) -> NVSDK_NGX_Result;
}
pub type PFN_NVSDK_NGX_Parameter_GetF = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f32,
    ) -> NVSDK_NGX_Result,
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetF(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f32,
    ) -> NVSDK_NGX_Result;
}
pub type PFN_NVSDK_NGX_Parameter_GetD = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f64,
    ) -> NVSDK_NGX_Result,
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetD(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut f64,
    ) -> NVSDK_NGX_Result;
}
pub type PFN_NVSDK_NGX_Parameter_GetUI = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_uint,
    ) -> NVSDK_NGX_Result,
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetUI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_uint,
    ) -> NVSDK_NGX_Result;
}
pub type PFN_NVSDK_NGX_Parameter_GetI = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_int,
    ) -> NVSDK_NGX_Result,
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetI(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut ::std::os::raw::c_int,
    ) -> NVSDK_NGX_Result;
}
pub type PFN_NVSDK_NGX_Parameter_GetVoidPointer = ::std::option::Option<
    unsafe extern "C" fn(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut *mut ::std::os::raw::c_void,
    ) -> NVSDK_NGX_Result,
>;
extern "C" {
    pub fn NVSDK_NGX_Parameter_GetVoidPointer(
        InParameter: *mut NVSDK_NGX_Parameter,
        InName: *const ::std::os::raw::c_char,
        OutValue: *mut *mut ::std::os::raw::c_void,
    ) -> NVSDK_NGX_Result;
}
pub type PFN_NVSDK_NGX_ProgressCallback_C =
    ::std::option::Option<unsafe extern "C" fn(InCurrentProgress: f32, OutShouldCancel: *mut bool)>;
extern "C" {
    pub fn NVSDK_NGX_UpdateFeature(
        ApplicationId: *const NVSDK_NGX_Application_Identifier,
        FeatureID: NVSDK_NGX_Feature,
    ) -> NVSDK_NGX_Result;
}
extern "C" {
    pub fn GetNGXResultAsString(InNGXResult: NVSDK_NGX_Result) -> *const wchar_t;
}
pub type PFN_NVSDK_NGX_DLSS_GetStatsCallback = ::std::option::Option<
    unsafe extern "C" fn(InParams: *mut NVSDK_NGX_Parameter) -> NVSDK_NGX_Result,
>;
pub type PFN_NVSDK_NGX_DLSS_GetOptimalSettingsCallback = ::std::option::Option<
    unsafe extern "C" fn(InParams: *mut NVSDK_NGX_Parameter) -> NVSDK_NGX_Result,
>;
impl NVSDK_NGX_DLSS_Denoise_Mode {
    pub const NVSDK_NGX_DLSS_Denoise_Mode_Off: NVSDK_NGX_DLSS_Denoise_Mode =
        NVSDK_NGX_DLSS_Denoise_Mode(0);
    pub const NVSDK_NGX_DLSS_Denoise_Mode_DLUnified: NVSDK_NGX_DLSS_Denoise_Mode =
        NVSDK_NGX_DLSS_Denoise_Mode(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_DLSS_Denoise_Mode(pub ::std::os::raw::c_int);
impl NVSDK_NGX_DLSS_Roughness_Mode {
    pub const NVSDK_NGX_DLSS_Roughness_Mode_Unpacked: NVSDK_NGX_DLSS_Roughness_Mode =
        NVSDK_NGX_DLSS_Roughness_Mode(0);
    pub const NVSDK_NGX_DLSS_Roughness_Mode_Packed: NVSDK_NGX_DLSS_Roughness_Mode =
        NVSDK_NGX_DLSS_Roughness_Mode(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_DLSS_Roughness_Mode(pub ::std::os::raw::c_int);
impl NVSDK_NGX_DLSS_Depth_Type {
    pub const NVSDK_NGX_DLSS_Depth_Type_Linear: NVSDK_NGX_DLSS_Depth_Type =
        NVSDK_NGX_DLSS_Depth_Type(0);
    pub const NVSDK_NGX_DLSS_Depth_Type_HW: NVSDK_NGX_DLSS_Depth_Type =
        NVSDK_NGX_DLSS_Depth_Type(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_DLSS_Depth_Type(pub ::std::os::raw::c_int);
impl NVSDK_NGX_RayReconstruction_Hint_Render_Preset {
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_Default:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(0);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_A:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(1);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_B:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(2);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_C:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(3);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_D:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(4);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_E:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(5);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_F:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(6);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_G:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(7);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_H:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(8);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_I:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(9);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_J:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(10);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_K:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(11);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_L:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(12);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_M:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(13);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_N:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(14);
    pub const NVSDK_NGX_RayReconstruction_Hint_Render_Preset_O:
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset =
        NVSDK_NGX_RayReconstruction_Hint_Render_Preset(15);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct NVSDK_NGX_RayReconstruction_Hint_Render_Preset(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NVSDK_NGX_DLSSD_Create_Params {
    pub InDenoiseMode: NVSDK_NGX_DLSS_Denoise_Mode,
    pub InRoughnessMode: NVSDK_NGX_DLSS_Roughness_Mode,
    pub InUseHWDepth: NVSDK_NGX_DLSS_Depth_Type,
    pub InWidth: ::std::os::raw::c_uint,
    pub InHeight: ::std::os::raw::c_uint,
    pub InTargetWidth: ::std::os::raw::c_uint,
    pub InTargetHeight: ::std::os::raw::c_uint,
    #[doc = " OPTIONAL"]
    pub InPerfQualityValue: NVSDK_NGX_PerfQuality_Value,
    pub InFeatureCreateFlags: ::std::os::raw::c_int,
    pub InEnableOutputSubrects: bool,
}
#[test]
fn bindgen_test_layout_NVSDK_NGX_DLSSD_Create_Params() {
    const UNINIT: ::std::mem::MaybeUninit<NVSDK_NGX_DLSSD_Create_Params> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<NVSDK_NGX_DLSSD_Create_Params>(),
        40usize,
        "Size of NVSDK_NGX_DLSSD_Create_Params"
    );
    assert_eq!(
        ::std::mem::align_of::<NVSDK_NGX_DLSSD_Create_Params>(),
        4usize,
        "Alignment of NVSDK_NGX_DLSSD_Create_Params"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InDenoiseMode) as usize - ptr as usize },
        0usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InDenoiseMode"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InRoughnessMode) as usize - ptr as usize },
        4usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InRoughnessMode"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InUseHWDepth) as usize - ptr as usize },
        8usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InUseHWDepth"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InWidth) as usize - ptr as usize },
        12usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InWidth"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InHeight) as usize - ptr as usize },
        16usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InHeight"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InTargetWidth) as usize - ptr as usize },
        20usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InTargetWidth"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InTargetHeight) as usize - ptr as usize },
        24usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InTargetHeight"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InPerfQualityValue) as usize - ptr as usize },
        28usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InPerfQualityValue"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InFeatureCreateFlags) as usize - ptr as usize },
        32usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InFeatureCreateFlags"
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).InEnableOutputSubrects) as usize - ptr as usize },
        36usize,
        "Offset of field: NVSDK_NGX_DLSSD_Create_Params::InEnableOutputSubrects"
    );
}
impl Default for NVSDK_NGX_DLSSD_Create_Params {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn HELPERS_NGX_DLSS_GET_OPTIMAL_SETTINGS(
        pInParams: *mut NVSDK_NGX_Parameter,
        InUserSelectedWidth: ::std::os::raw::c_uint,
        InUserSelectedHeight: ::std::os::raw::c_uint,
        InPerfQualityValue: NVSDK_NGX_PerfQuality_Value,
        pOutRenderOptimalWidth: *mut ::std::os::raw::c_uint,
        pOutRenderOptimalHeight: *mut ::std::os::raw::c_uint,
        pOutRenderMaxWidth: *mut ::std::os::raw::c_uint,
        pOutRenderMaxHeight: *mut ::std::os::raw::c_uint,
        pOutRenderMinWidth: *mut ::std::os::raw::c_uint,
        pOutRenderMinHeight: *mut ::std::os::raw::c_uint,
        pOutSharpness: *mut f32,
    ) -> NVSDK_NGX_Result;
}
